
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://orvuvpukuksbewsvbazw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydnV2cHVrdWtzYmV3c3ZiYXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODU5OTEsImV4cCI6MjA1Njg2MTk5MX0.Q_5vURcMQ_Q_Cj2tMHMQD64C4cN7MhdI83lcjIqyDPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
